version: '3.9'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  test_db:
    image: postgres
    restart: always
    env_file:
      - test_db.env
    ports:
      - "6000:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  warehouse-api:
    build:
      dockerfile: Dockerfile
    image: warehouse-api:latest
    restart: always
    container_name: warehouse-api-dev
    depends_on:
      - db
    ports:
      - "8080:8000"
    volumes:
      - .:/warehouse-api
    networks:
      - backend

volumes:
  postgres_data:
  test_postgres_data:

networks:
  backend:
    driver: bridge